# This is a basic example Blueprint for a Django web service and
# the PostgreSQL database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    plan: free
    name: react
    runtime: docker
    dockerContext: ./
    repo: hhttps://github.com/Loise/ci-cd-ynov.git
    dockerfilePath: ./DockerfileReact
    envVars:
      - key: REACT_APP_SERVER_URL # Sets DATABASE_URL to the connection string of the django-app-db database